### ISSUE TITLE
OSError: No write intent on file (no write intent on file)

### ISSUE THREAD

**Issue by afushiki** [bermanlabemory/motionmapperpy#1]
HI! Thank you for sharing this MotionMapper python code. When I ran the demo code (demo.py), I received the following error:

~/motionmapperpy$ python3 demo/demo.py
...
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 50, in h5py.h5a.create
OSError: No write intent on file (no write intent on file)

Can anyone please help in sorting out this issue?

**Comment by kanishkbjain** [comment]
Thank you for posting this, I was able to reproduce the issue. It is being caused by hdf5storage package, which seems to have a dependency conflict with h5py3.x.

I was able to circumvent the issue by downgrading to h5py2.10

``conda activate $YOURENVIRONMENTNAME``
``pip install -U h5py==2.10``

Please let me know if this works for you as well.

**Comment by afushiki** [comment]
Yes, it worked! Thank you for your quick response.
